#!/bin/bash

# Build and Flash script for Pro Micro Leonardo
# Board: SparkFun Pro Micro (ATmega32U4, 5V/16MHz)
# ESP-ProMicro-HidKey v2.0 - Security Upgrade

set -e

# Use system arduino-cli if available, otherwise fall back to a local bin/arduino-cli
ARDUINO_CLI="${ARDUINO_CLI:-arduino-cli}"
SKETCH_DIR="$(dirname "$(realpath "$0")")"
BOARD="arduino:avr:leonardo"
PORT="${1:-/dev/ttyACM0}"

echo "═══════════════════════════════════════════════════════════"
echo "  ESP-ProMicro-HidKey v2.0 - Build Script"
echo "═══════════════════════════════════════════════════════════"
echo "Sketch: $SKETCH_DIR"
echo "Port: $PORT"
echo ""

# Check if .env exists
if [ ! -f "$SKETCH_DIR/.env" ]; then
    echo "⚠️  Warning: .env file not found!"
    echo "   Creating a template .env with a generated AES_MASTER_KEY and an example combination."

    # Generate a random 16-byte (32 hex chars) AES key using Python's secrets
    AES_KEY=$(python3 - <<'PY'
import secrets
print(secrets.token_hex(16).upper())
PY
)

    cat > "$SKETCH_DIR/.env" <<EOF
# Auto-generated .env for ESP-ProMicro-HidKey
AES_MASTER_KEY=${AES_KEY}
COMBINATION_COUNT=1
COMBINATION_0_SEQUENCE=0,1,0
COMBINATION_0_PASSWORD=your_password_here
SEQUENCE_TIMEOUT_MS=3000  # milliseconds of inactivity before sequence recognition
EOF

    echo "✅ Created $SKETCH_DIR/.env — edit COMBINATION_* or SEQUENCE_TIMEOUT_MS values before building"
else
    # Step 1: Generate encrypted password header
    echo "📝 Generating encrypted password header..."
    cd "$SKETCH_DIR"
    python3 generate_password_header.py
    if [ $? -eq 0 ]; then
        echo "✅ Generated: embedded_passwords.h (AES-CBC + ChaCha20)"
    else
        echo "❌ Failed to generate password header"
        exit 1
    fi
    echo ""
fi

# Install board cores if necessary
if ! $ARDUINO_CLI core list | grep -q "arduino:avr"; then
    echo "Installing Arduino AVR Core..."
    $ARDUINO_CLI core install arduino:avr
fi

if ! $ARDUINO_CLI core list | grep -q "SparkFun:avr"; then
    echo "Installing SparkFun AVR Core..."
    $ARDUINO_CLI core install SparkFun:avr --additional-urls https://raw.githubusercontent.com/sparkfun/Arduino_Boards/main/IDE_Board_Manager/package_sparkfun_index.json
fi

# Generate build_config.h from .env (SEQUENCE_TIMEOUT_MS)
SEQ_TIMEOUT_MS=$(grep -E '^SEQUENCE_TIMEOUT_MS=' "$SKETCH_DIR/.env" | cut -d= -f2 | sed -E 's/[[:space:]]*#.*//' | tr -d '[:space:]' || true)
if [ -z "$SEQ_TIMEOUT_MS" ]; then
    SEQ_TIMEOUT_MS=3000
fi
cat > "$SKETCH_DIR/build_config.h" <<EOF
// Auto-generated by build.sh
#pragma once
#define SEQUENCE_TIMEOUT_MS ${SEQ_TIMEOUT_MS}
EOF

echo "🛠  Generated build_config.h (SEQUENCE_TIMEOUT_MS=${SEQ_TIMEOUT_MS})"

# Compile
# Always use the main sketch file specifically (avoid compiling EEPROM_Clear.ino)
MAIN_SKETCH="$SKETCH_DIR/ESP-ProMicro-HidKey.ino"

if [ -f "$MAIN_SKETCH" ]; then
    echo "Compiling sketch: $MAIN_SKETCH"
else
    echo "❌ Main sketch not found: $MAIN_SKETCH"
    exit 1
fi

$ARDUINO_CLI compile -v --fqbn "$BOARD" "$MAIN_SKETCH"

if [ $? -ne 0 ]; then
    echo "❌ Kompilierung fehlgeschlagen!"
    exit 1
fi

echo ""
echo "✅ Kompilierung erfolgreich!"
echo ""

# Flash
echo "Flashing to $PORT..."
echo "(If necessary: press the Reset button on the Pro Micro)"
$ARDUINO_CLI upload -v -p "$PORT" --fqbn "$BOARD" "$MAIN_SKETCH"

if [ $? -eq 0 ]; then
    echo ""
    echo "═══════════════════════════════════════════════════════════"
    echo "✅ SUCCESS! Device programmed"
    echo "═══════════════════════════════════════════════════════════"
    echo ""
    echo "🔄 First boot behavior:"
    echo "   - LED will blink during Stage-2 re-encryption"
    echo "   - Device ID generated with improved entropy"
    echo "   - Passwords re-encrypted with ChaCha20"
    echo "   - Ready indicator: 2 blinks"
    echo ""
    echo "🎮 Usage:"
    echo "   - Enter button sequence (short/long presses)"
    echo "   - Device will type password on match"
    echo "   - 3 seconds timeout between presses"
    echo ""
    echo "🔒 Security improvements v2.0:"
    echo "   ✅ AES-CBC with IV (instead of ECB)"
    echo "   ✅ ChaCha20 (instead of XOR)"
    echo "   ✅ HKDF-SHA256 (instead of simple XOR)"
    echo "   ✅ Better Device ID entropy"
    echo ""
    echo "📖 Read SECURITY_UPGRADE.md for details"
    echo ""
else
    echo ""
    echo "❌ Upload failed. Try:"
    echo "  1. Press the Reset button and run the script immediately"
    echo "  2. Specify a different port: ./build.sh /dev/ttyACM1"
    echo "  3. Check the USB connection"
fi
