// ╔══════════════════════════════════════════════════════════════════╗
// ║  Secure HID Pro Micro - Main Controller                         ║
// ║  Arduino Pro Micro (ATmega32u4) USB HID Keyboard                 ║
// ║  Compile-Time Encryption + Device Signature Authentication       ║
// ╚══════════════════════════════════════════════════════════════════╝
//
// Security Features:
// - AES-128 encrypted passwords (compile-time)
// - Device signature-based key derivation
// - Anti-timing sequence detection (5-second window)
// - Fake password for duress scenarios
// - Lock after 3 failed attempts
// - Zero plaintext in binary or RAM (wiped after use)

#include <Keyboard.h>
#include <HID.h>
#include <EEPROM.h>

// Include generated secrets header (auto-generated by build.sh)
#ifdef SECURE_HID_BUILD
#include "secrets.h"
#endif

// ===== HARDWARE PINS =====
const int BUTTON_PIN = 9;   // Digital pin 9
const int LED_PIN = 10;     // External LED (Pro Micro D10)

// ===== TIMING CONSTANTS =====
const unsigned long LONG_PRESS_MS = 500;       // Long press threshold
const unsigned long INPUT_WINDOW_MS = 5000;    // 5-second input window
const unsigned long DEBOUNCE_MS = 50;          // Debounce delay

// ===== UNLOCK SEQUENCES =====// First sequence: Unlock (S=Short, L=Long press)
const char SEQ_UNLOCK[] = {'S', 'S', 'L', 'S'};
const int SEQ_UNLOCK_LEN = 4;

// Second sequence: Password selection (after unlock)
const char SEQ_PASSWORD_1[] = {'S', 'S'};
const char SEQ_PASSWORD_2[] = {'L', 'S'};
const char SEQ_FAKE[] = {'L', 'L'};
const int SEQ_MODE_LEN = 2;

// ===== BUFFER SIZES =====
const int INPUT_BUFFER_SIZE = 8;
const int PASSWORD_BUFFER_SIZE = 64;

// ===== STATE MACHINE =====
enum DeviceState {
  STATE_IDLE,              // Waiting for first button press
  STATE_COLLECTING_UNLOCK, // Collecting unlock sequence
  STATE_COLLECTING_MODE,   // Collecting password selection sequence
  STATE_LOCKED             // Device locked (3 failed attempts)
};

DeviceState currentState = STATE_IDLE;
char inputBuffer[INPUT_BUFFER_SIZE];  // Buffer for button sequence
int bufferIndex = 0;
unsigned long windowStartTime = 0;
bool inputWindowActive = false;

// Security counters
int failedUnlockAttempts = 0;
const int MAX_FAILED_ATTEMPTS = 3;

// Button debouncing
bool lastButtonState = HIGH;      // HIGH = not pressed (INPUT_PULLUP)
unsigned long buttonPressStartTime = 0;
bool buttonPressed = false;

// ===== FUNCTION DECLARATIONS (defined in other .ino files) =====
// From crypto_core.ino
void initCrypto();
void decryptPassword(const uint8_t* encrypted, size_t encLen, char* output, size_t maxLen);

// From hid_controller.ino
void sendPasswordViaHID(const char* password);

// From utils.ino
void blinkLED(int count, int delayMs = 120);
void setLED(bool state);

// ===== SETUP =====
void setup() {
  // Initialize hardware pins
  pinMode(BUTTON_PIN, INPUT_PULLUP);
  pinMode(LED_PIN, OUTPUT);
  digitalWrite(LED_PIN, LOW);
  
  // Initialize USB HID keyboard
  Keyboard.begin();
  delay(1000);  // Give USB HID time to fully initialize
  
  // Initialize crypto subsystem
  initCrypto();
  
  // Startup LED indicator (2 quick blinks)
  blinkLED(2, 100);
  
  // Reset state
  currentState = STATE_IDLE;
  bufferIndex = 0;
  inputWindowActive = false;
}

// ===== MAIN LOOP =====
void loop() {
  // Handle locked state - use non-blocking approach
  if (currentState == STATE_LOCKED) {
    static unsigned long lastBlink = 0;
    unsigned long now = millis();
    
    // Blink LED slowly when locked (every 500ms toggle)
    if (now - lastBlink >= 500) {
      static bool ledState = false;
      ledState = !ledState;
      setLED(ledState);
      lastBlink = now;
    }
    
    // In locked state, still check button to allow power cycle detection
    // But don't process sequences
    return;
  }
  
  // Read button input
  handleButtonInput();
  
  // Check if input window expired
  if (inputWindowActive && (millis() - windowStartTime >= INPUT_WINDOW_MS)) {
    evaluateSequence();
    resetInputBuffer();
  }
}

// ===== BUTTON INPUT HANDLER =====
void handleButtonInput() {
  bool currentButtonState = digitalRead(BUTTON_PIN);
  
  // Button press detected (transition from HIGH to LOW)
  if (currentButtonState == LOW && lastButtonState == HIGH) {
    // Debounce: wait to confirm stable LOW state
    delay(DEBOUNCE_MS);
    if (digitalRead(BUTTON_PIN) == LOW) {
      buttonPressed = true;
      buttonPressStartTime = millis();
      
      // Start/reset input window on every press (5 seconds from last button)
      inputWindowActive = true;
      windowStartTime = millis();
    }
  }
  
  // Button release detected (transition from LOW to HIGH)
  if (currentButtonState == HIGH && lastButtonState == LOW && buttonPressed) {
    // Debounce: wait to confirm stable HIGH state
    delay(DEBOUNCE_MS);
    if (digitalRead(BUTTON_PIN) == HIGH) {
      buttonPressed = false;
      
      // Calculate press duration
      unsigned long pressDuration = millis() - buttonPressStartTime;
      
      // Determine press type
      char pressType = (pressDuration < LONG_PRESS_MS) ? 'S' : 'L';
      
      // Add to buffer with explicit bounds check
      if (bufferIndex < INPUT_BUFFER_SIZE) {
        inputBuffer[bufferIndex++] = pressType;
        blinkLED(1, 80);  // Quick feedback blink
        
        // Check if we have enough input to evaluate immediately
        bool shouldEvaluate = false;
        
        if (currentState == STATE_IDLE && bufferIndex >= SEQ_UNLOCK_LEN) {
          shouldEvaluate = true;
        } else if (currentState == STATE_COLLECTING_MODE && bufferIndex >= SEQ_MODE_LEN) {
          shouldEvaluate = true;
        }
        
        // Evaluate immediately if sequence is complete
        if (shouldEvaluate) {
          delay(100);  // Brief pause for stability
          evaluateSequence();
        }
      }
    }
  }
  
  lastButtonState = currentButtonState;
}

// ===== SEQUENCE EVALUATION =====
void evaluateSequence() {
  if (currentState == STATE_IDLE) {
    // Check unlock sequence
    if (bufferIndex == SEQ_UNLOCK_LEN && 
        memcmp(inputBuffer, SEQ_UNLOCK, SEQ_UNLOCK_LEN) == 0) {
      
      // Unlock successful
      currentState = STATE_COLLECTING_MODE;
      failedUnlockAttempts = 0;
      blinkLED(5, 100);  // 5 blinks = success
      resetInputBuffer();  // Clear buffer for password selection
      delay(200);  // Brief pause before accepting password selection
      
    } else {
      // Wrong unlock sequence
      failedUnlockAttempts++;
      blinkLED(3, 150);  // 3 blinks = error
      
      // Lock device after max attempts
      if (failedUnlockAttempts >= MAX_FAILED_ATTEMPTS) {
        currentState = STATE_LOCKED;
      }
    }
    
  } else if (currentState == STATE_COLLECTING_MODE) {
    // Check password selection sequence
    if (bufferIndex == SEQ_MODE_LEN) {
      
      if (memcmp(inputBuffer, SEQ_PASSWORD_1, SEQ_MODE_LEN) == 0) {
        // Password 1
        outputPassword(1);
        
      } else if (memcmp(inputBuffer, SEQ_PASSWORD_2, SEQ_MODE_LEN) == 0) {
        // Password 2
        outputPassword(2);
        
      } else if (memcmp(inputBuffer, SEQ_FAKE, SEQ_MODE_LEN) == 0) {
        // Fake password (duress mode)
        outputPassword(0);
        
      } else {
        // Unknown sequence - send fake password
        outputPassword(0);
      }
    } else {
      // Wrong length - send fake password
      outputPassword(0);
    }
    
    // Return to idle state
    currentState = STATE_IDLE;
    inputWindowActive = false;
  } else {
    // Unknown state - reset
    inputWindowActive = false;
  }
}

// ===== PASSWORD OUTPUT =====
void outputPassword(int passwordNumber) {
  char decryptedPassword[PASSWORD_BUFFER_SIZE];
  memset(decryptedPassword, 0, sizeof(decryptedPassword));
  
  #ifdef SECURE_HID_BUILD
  // Decrypt appropriate password
  switch (passwordNumber) {
    case 1:
      decryptPassword(SECRET_1_ENCRYPTED, SECRET_1_ENCRYPTED_LEN, 
                      decryptedPassword, sizeof(decryptedPassword));
      break;
      
    case 2:
      decryptPassword(SECRET_2_ENCRYPTED, SECRET_2_ENCRYPTED_LEN, 
                      decryptedPassword, sizeof(decryptedPassword));
      break;
      
    case 0:  // Fake password
    default:
      decryptPassword(FAKE_PASSWORD_ENCRYPTED, FAKE_PASSWORD_ENCRYPTED_LEN, 
                      decryptedPassword, sizeof(decryptedPassword));
      break;
  }
  #else
  // Fallback if secrets.h not available (dev mode)
  strcpy(decryptedPassword, "TestPassword123");
  #endif
  
  // Send via USB HID
  sendPasswordViaHID(decryptedPassword);
  
  // CRITICAL: Securely wipe plaintext from RAM
  memset(decryptedPassword, 0, sizeof(decryptedPassword));
}

// ===== UTILITY FUNCTIONS =====
void resetInputBuffer() {
  bufferIndex = 0;
  memset(inputBuffer, 0, sizeof(inputBuffer));
  inputWindowActive = false;
}

